### ISSUE TITLE
环境变量MEMBER_IDS格式是啥样的？

### ISSUE THREAD

**Issue by curx95** [C-racker/auto-sign#2]
我直接把member_id用“,”号传入，发现有问题。authorization也要传入，所以格式应该是member_id=xxxx;authorization=xxx;,member_id=yyyy;authorization=yyyy; 这样吗？

**Comment by C-racker** [comment]
是的，多账号用逗号隔开。member_id=xxxx;authorization=xxx,member_id=yyyy;authorization=yyyy
